### ISSUE TITLE
نماینده فروش (reseller)

### ISSUE THREAD

**Issue by mojtabakhani** [test-group-qom/reseller#1]
در پایان این تسک موارد ذیل انتظار میرود:

1. ایجاد 
    migration
    model
    soft delete
    seed.
2. ایجاد کنترولر با API های:
    list show 
    single show by id
    insert a new reseller 
    update a reseller by id
    delete a reseller by id

3. اطلاعات یک نماینده فروش :
    id(index, auto increment)*
    name(string)*
    username(string,unique)*
    token(string,unique)
    mobile(string)*
    bank_card(string)
    status(integer)[0=>invalid , 1=>active . 2 inactive]

**Comment by birturk90** [comment]
that project finished
